### ISSUE TITLE
Question: why not standart method names?

### ISSUE THREAD

**Issue by snowyurik** [Steve-Fenton/tsUnit#15]
It will be much easier to use tsUnit if there are standard methods:

setUp(), tearDown(), assertTrue(), assertEquals() /* instead of areIdentical() */, etc. 

Steve, it's up to you, sure. But I use TDD for years and it will be much easier to people like me to use standard named methods. Unit test for CPP, Java, Php, Javascript(with qunit) are very similar. Even if you had not used qunit before, but have experience with JUnit - you can just guess and it will work fine in most cases. But for tsUnit you need to memorize new method names. 

Also, you won't need to pay so much attention to documentation - people already expect some behaviour, if tsUnit will match this behaviour - they will heve no need in documentation. That can make tsUnit more popular. Otherwize, someone might create alternative framework.

What do you think?

**Comment by Steve-Fenton** [comment]
Because JavaScript had some unique rules regarding juggling types used in a comparison there are two different methods of comparison.

The first allows the special comparisons that JavaScript does, often referred to add 'truthy' and 'falsey'. This will treat things such as null, undefined, 0, and empty strings as false even though their type is not boolean.

To make this a conscious choice, the assertions make the difference apparent to the programmer.

isTruthy makes it clear that you are happy to accept that 59, 'hello', and { x: 0 } are ask examples of 'true'.

are identical makes it clear that both type and value must match, so 1 does not equal '1'.

If there was broad agreement on which style of comparison should apply, I would be happy to add an alias for the assertions.

**Comment by Steve-Fenton** [comment]
Apologies for closing the issue, which I intended to leave open for further discussion. I scroll-clicked "Close and Comment" on my phone. I have re-opened.

**Comment by snowyurik** [comment]
Thanks for your reply Steve. 
I recognize difference between isTrue and isTruthly. That's great. TsUnit is great. Thank you very much for creating it. However I'm talking about different thing:

TDD dev with some experience in other languages will expect methods named 'assertTrue' and/or 'assertTruthly'. **How about adding such methods as aliases for 'isTrue', 'isTruthly' etc? **

Just: 
**protected assertTrue(actual: boolean, message = '') { return isTrue(actual, message);}**

In this case you will have backward compatibility and tsUnit will be more like unit-testing frameworks for the other languages. It will be simpler to start using tsUnit, and also you will get some help from IDEs. If all assertion methods start from 'assert', you can just type 'this.assert' and than choose proper method from dropdown list. 

We have a lot of tests, you know. If your project is 100% covered with unit test - there will be almost the same lines count in tests as in code. So even if you simplify writing tests a little bit  - it will reduce time for creating application a lot.
