### ISSUE TITLE
Async Support?

### ISSUE THREAD

**Issue by geniuscodemonkey** [Steve-Fenton/tsUnit#16]
I would really like to roll out tsUnit within my company for unit testing TypeScript as I don't really like Jasmine; but the one main blocker we have at the moment is that tsUnit doesn't support async calls.
With async calls and karma support; tsUnit could be really big.

**Comment by Steve-Fenton** [comment]
:+1:

**Comment by hn3000** [comment]
Would you be interested in getting a PR for this?

**Comment by Steve-Fenton** [comment]
Absolutely - I'd be delighted :)

**Comment by Steve-Fenton** [comment]
Package uploaded to NuGet: https://www.nuget.org/packages/tsUnit/

**Comment by hn3000** [comment]
Just a note: in working with the code as an npm module I noticed that it's not ideal that I defined the Promise API locally because it could lead to duplicate symbol errors. It might be better to use es6-promise, but I could not figure out how to add that as a dependency here. Another problem was that I only have VS 2015 in a VM and it asked me to convert the project files before it was willing to work with the project -- and the conversion for one of the projects failed, unfortunately.

**Comment by Steve-Fenton** [comment]
Package uploaded to NPM: https://www.npmjs.com/package/tsunit.external.

**Comment by hn3000** [comment]
Another thing I just realized: because I did not change the Visual Studio or the package infrastructure your packages ended up not containing the new code. (Sorry about that.) For the npm package we should at least the main entry to point at the new tsUnitAsync file and ensure that all the necessary files are copied over, for the nuGet package I have no idea what needs to be done, unfortunately.

**Comment by Steve-Fenton** [comment]
Don't worry - the NPM example project requires a Visual Studio extension. We can always add dependencies to the package.json for NPM if people need us to change it. I'll let people raise an issue if they have any problems - the NPM example project works fine.

**Comment by hn3000** [comment]
Oh right, I also overlooked that example, I should have added an async example there as well -- it only works because it does not try to use the async test runner.

**Comment by Steve-Fenton** [comment]
I updated all the packages and examples here:

https://github.com/Steve-Fenton/tsUnit/commit/98955a34b45d807904de06faf915eb02569189a8

Let me update the node example and see what happens :)
