### ISSUE TITLE
Forks can not be installed via npm with git url

### ISSUE THREAD

**Issue by hn3000** [Steve-Fenton/tsUnit#21]
Because the package.json is deep inside the project structure, the module can not be installed straight from git. 

Since tsunit now uses the umd module format, it should be possible to move the package.json to the top and get rid of the copying at least for npm. (And that would also reduce the problem with contributors who forget to properly adapt the build scripts ...)

What do you think?

**Comment by hn3000** [comment]
Details about the issue with installation from git:
* [npm #2974](https://github.com/npm/npm/issues/2974#issuecomment-169451651)
* [MS nodejstools #471](https://github.com/Microsoft/nodejstools/issues/471)

**Comment by Steve-Fenton** [comment]
That's not a bad idea - the packaging so has some hangovers from the pre-UMD set up (I used to have to automate additional lines of code in one of the packages).
-------- Original message --------From: hn3000 <notifications@github.com> Date: 10/07/2016  13:48  (GMT+00:00) To: Steve-Fenton/tsUnit <tsUnit@noreply.github.com> Subject: [Steve-Fenton/tsUnit] Forks can not be installed via npm with git url (#21) 
Because the package.json is deep inside the project structure, the module can not be installed straight from git. 

Since tsunit now uses the umd module format, it should be possible to move the package.json to the top and get rid of the copying at least for npm. (And that would also reduce the problem with contributors who forget to properly adapt the build scripts ...)

What do you think?

**Comment by Steve-Fenton** [comment]
The packaging strategy has been totally overhauled. How are we for this now those charges are done?

**Comment by Steve-Fenton** [comment]
Assuming at this point the changes worked!
